### ISSUE TITLE
Add a function to translate more easily timestamp_mesure to an R class datetime POSIXct

### ISSUE THREAD

**Issue by marqisoft** [inrae/hubeau#13]
Real time piezometric data is tied to precise date AND time. That information is exported in the timestamp_mesure field. Could you create a little function to help us translate the timestamps into POSIXct datetimes in R?

Or if you are okay to modify the output table generated by your package's get function, that could even (or also) be done inside the relevant get functions; the one I see for now is: get_niveaux_nappes_chroniques_tr.

By the way, thanks for this package, it works well and is very helpful!

**Comment by DDorch** [comment]
Can you give an example where the fields `date_mesure` and `timestamp_mesure` give incoherent results?

Here below, I try a conversion of both fields and they return same date-time:

``` r
> library(dplyr)
> get_niveaux_nappes_chroniques_tr(list(code_bss="07548X0009%2FF", 
                                        date_debut_mesure="2022-08-01", 
                                        fields = "timestamp_mesure,date_mesure,niveau_eau_ngf")) %>% 
    mutate(date_from_date = lubridate::ymd_hms(date_mesure), 
           date_from_timestamp = as.POSIXct(timestamp_mesure / 1000, origin = "1970-01-01", tz = "UTC"))
```
```
# A tibble: 673 × 5
   date_mesure          timestamp_mesure niveau_e…¹ date_from_date      date_from_timestamp
   <chr>                           <dbl>      <dbl> <dttm>              <dttm>             
 1 2022-08-30T00:00:00Z    1661817600000       21.5 2022-08-30 00:00:00 2022-08-30 00:00:00
 2 2022-08-29T23:00:00Z    1661814000000       21.6 2022-08-29 23:00:00 2022-08-29 23:00:00
 3 2022-08-29T22:00:00Z    1661810400000       21.8 2022-08-29 22:00:00 2022-08-29 22:00:00
 4 2022-08-29T21:00:00Z    1661806800000       22.0 2022-08-29 21:00:00 2022-08-29 21:00:00
 5 2022-08-29T20:00:00Z    1661803200000       22.1 2022-08-29 20:00:00 2022-08-29 20:00:00
 6 2022-08-29T19:00:00Z    1661799600000       22.0 2022-08-29 19:00:00 2022-08-29 19:00:00
 7 2022-08-29T18:00:00Z    1661796000000       21.9 2022-08-29 18:00:00 2022-08-29 18:00:00
 8 2022-08-29T17:00:00Z    1661792400000       21.8 2022-08-29 17:00:00 2022-08-29 17:00:00
 9 2022-08-29T16:00:00Z    1661788800000       21.6 2022-08-29 16:00:00 2022-08-29 16:00:00
10 2022-08-29T15:00:00Z    1661785200000       21.4 2022-08-29 15:00:00 2022-08-29 15:00:00
# … with 663 more rows, and abbreviated variable name ¹​niveau_eau_ngf
# ℹ Use `print(n = ...)` to see more rows
```

When you do the conversion to date time, you can meet time zone conversion issues. `as.POSIXct` convert timestamp to system time zone by default (local time on Windows, and UTC on Linux). Here I needed to specify `tz="UTC"` on `as.POSIXct` to get same result as `date_from_date`. I can also specify `tz="Europe/paris"` on `ymd_hms` to get the two columns in local date time. I'm afraid that it is not straightforward to automate a conversion adapted to everyone needs and the conversion is not difficult to do especially with the lubridate function `ymd_hms`.

**Comment by marqisoft** [comment]
Oops, really sorry, you are right: date_mesure can be translated into precise Date and Time. I guess I mixed up with previous tests where I had skipped the Time part. So everything is okay. Thanks for your very fast reply!
