### ISSUE TITLE
Fonctions de requêtage de l'ensemble des API Hub'eau ?

### ISSUE THREAD

**Issue by PascalIrz** [inrae/hubeau#2]
Hi,
Is there a possibility that the package extends to query all the 12 APIs of the Hub'eau platform? I suppose it would meet some needs. A united framework would be very useful particularly for the users working with several of these datasets.
Regards.
Pascal

**Comment by DDorch** [comment]
Other API implementations are describes in dedicated issues: #5, #6, #7, #8, #9, and #10
