### ISSUE TITLE
Passage à la v1 de l'API écoulement

### ISSUE THREAD

**Issue by CedricMondy** [inrae/hubeau#33]
Le 23 mai 2023, l'API écoulement va passer en v1, [les appels via des URLs utilisant la vbeta ne seront plus fonctionnels](https://github.com/richaben/PRR_ONDE/issues/14).
Il faudrait donc changer la configuration de l'API dans l'objet .cfg

**Comment by OFB-IdF** [comment]
j'ai ouvert une PR pour faire le changement #34
